### ISSUE TITLE
Excel output

### ISSUE THREAD

**Issue by evelinekeh** [ghbonne/PMConverter#1]
"In de Excel outputs zijn de kolommen Fixed Cost en Variable Cost lichtgroen geworden (alternative input) en de kolom Cost/Hour donkergroen (necessary input), terwijl dit in de originele sheet net omgekeerd is."
IMPORTANT: first check if there is a reason for this or just a stupid bug.

**Comment by ghbonne** [comment]
The used colours are indeed switched by mistake.
But the hourly cost is currently used prior input to the variable cost field, so that should also be switched to match the correct colour code.

**Comment by GillesVandewiele** [comment]
Will be fixed by fixing #14
