### ISSUE TITLE
Xlsxparser: evaluate read Excel functions

### ISSUE THREAD

**Issue by ghbonne** [ghbonne/PMConverter#12]
Be able to handle excel functions as input instead of solely text, numbers and dates.

the used xlsx library has some Excel function evaluation functionality, but it has to be used within PMConverter

**Comment by GillesVandewiele** [comment]
Sommige velden kunnen bv een SUM(...) of AVG(...) bevatten, deze kunnen momenteel niet worden ingelezen (TESTEN) en moeten worden ondersteund.

**Comment by ghbonne** [comment]
Think also of a simple reference to another cell: e.g. "=A5" which can currently not be handled by PMConverter

**Comment by GillesVandewiele** [comment]
Seems like the load_workbook function had a data_only flag. Putting this on True results in reading the results of the functions instead of the function itself.
