### ISSUE TITLE
Update colour codes of output Excel files

### ISSUE THREAD

**Issue by ghbonne** [ghbonne/PMConverter#14]
The colour codes used in the new Excel format are a bit different from the ones used  in the previous extended and basic Excel version.

**Comment by GillesVandewiele** [comment]
So if I'm right in this, I would only need a yellow, green and gray color for each column. And maybe a fourth extra color to indicate activities of higher level?

**Comment by ghbonne** [comment]
Indeed, I think so. 
Just like the reference excel format sheet

**Comment by ghbonne** [comment]
Extra colour changements:
general info (project ID and Name) in the Risk Analysis tab and the Project Control tabs are necessary input.
Should we throw an exception when these fields are not filled in?
And/or should we check if the name corresponds with the ID in our dicts?

**Comment by ghbonne** [comment]
Update: Only the activity Id is necessary input
