### ISSUE TITLE
Excel: resources tab: consumable resources don't have an availability

### ISSUE THREAD

**Issue by ghbonne** [ghbonne/PMConverter#16]
Currently the xlsxparser requires that every resource has an availability given in the resources tab, this is undesired for consumable resources.

Todo: If a resource is of the type "Consumable", the parser should not read the availability cell, but skip it.

**Comment by GillesVandewiele** [comment]
if res_type != ResourceType.CONSUMABLE:
                # Had to cast string -> float -> int (silly Python!)
                res_ava = int(float(resource_sheet.cell(row=curr_row, column=4).value.split(" ")[0]
                          .translate(str.maketrans(",", "."))))
            else:
                res_ava = 0
