### ISSUE TITLE
resource unit

### ISSUE THREAD

**Issue by ghbonne** [ghbonne/PMConverter#17]
PMConverter currently uses the assumption to append a "#availability" string to the resource availability in the resources tab, as well as to a resource assignment in the baseline schedule tab.

In fact ProTrack would want this to be the resource's unit, instead of repeating the availability.

**Desired format:**
### Baseline schedule tab: Resource demand column
Still append the "#availability" to the resource demand, cf. “carpenter[3,00 #3]” for PMConvert's output.
But PMConverter's input should also allow that the "#availability" is not given: cf. “carpenter[3,00]”.
(current implementation should already be OK, but check it)

### Resources tab: Resource availability
Don't append the "#availability" to the default availability quantity, but append its resource unit as defined in ProTrack, this can be empty (e.g. "3.0") or e.g. "3.0 laborer".
So PMConverter needs also to read this unit from the input Excel file if it is given, and store it in the resource object.

This issue has an effect on **Xlsxparser**, **XMLparser** and **project object**

**Comment by GillesVandewiele** [comment]
#availability in the baseline schedule tab was indeed already optional.

I changed the '#availability' by ' name' in the resource tab, which seems useless again, but probably i misinterpreted this and I need to add a new field in the project object, and read/write it in XML + XLSX?

**Comment by ghbonne** [comment]
Quote GillesVandewiele: "*I need to add a new field in the project object, and read/write it in XML + XLSX*" 
Yes indeed, and it should be called resourceUnit or something in that trend.

But Jordy indicated that in the baseline schedule tab it could still remain " #availability" because that is easy to read.
But in the resource tab, the resource availabitlity column should be "availability resourceUnit" (instead of currently "availability #availability" ) and if the " resourceUnit" part is present, PMConverter should read it and store it in the project object.

**Comment by GillesVandewiele** [comment]
Ok the last-mentioned is already realised. But atm "availability name" is being printed. I'll fix that resourceUnit later, after fixing the more easy issues ;)

**Comment by GillesVandewiele** [comment]
XML File: <FIELD778>arbeiders</FIELD778>
