### ISSUE TITLE
Excel to ProTrack activity trackingperiod recently started issues

### ISSUE THREAD

**Issue by ghbonne** [ghbonne/PMConverter#26]
Issue when converting Excel to ProTrack of just started activities (e.g. 1h):
 Zo is er bv een project met twee activiteiten die voor een bepaalde tracking periode nog maar net gestart zijn en dus nog maar een actual duration van 1h hebben. In de Excel input sheet hebben die een PC van 1%. Bij omzetting naar ProTrack hebben deze activiteiten ineens een PC van 62% en 60%, en ook de remaining duration is ineens maar 1h geworden ipv 20d 3h en 20d 7h volgens de Excel.

Bug traces: see mail files: 
- *C2015-29 Fire Station_converted_03_154752.xlsx*
- *C2015-29 Fire Station_converted_03_154752_converted_03_154914.p2x*

The issue can be seen in TP5 (30/03, 2011) for activities 190 and 193. 
Dus de Excel is juist, de geconverteerde ProTrack file bevat het foutje.

**Comment by GillesVandewiele** [comment]
This seems like a weird ProTrack bug. I've reconstructed the bug trace and opened ProTrack. If I then clicked on the duration of the activity with id 0 (so the project duration), a popup showed-up to set settings. I didn't change anything and just pressed OK, and automagically, everything was fixed.
