### ISSUE TITLE
Performance metrics layout

### ISSUE THREAD

**Issue by evelinekeh** [ghbonne/PMConverter#4]
* CPI and SPI(t) on the same graph,
* SPI(t), SPI and p-factor on the same graph
* change order of CV and SV(t)

**Comment by evelinekeh** [comment]
@ghbonne : the order of the visualisations of the tracking overview is now determined by the order the user select them in de UI. Can you change this behaviour by a predefined order, namely the order as defined in the 'processor'.

**Comment by ghbonne** [comment]
The user has now full control over the order of the selected visualisations in the output Excel tabs.
The order of tabs is determined by the order of the chosen visualisations in the GUI visualisation list, which can be changed at will by dragging and dropping
