### ISSUE TITLE
Excel to ProTrack: start and end dates

### ISSUE THREAD

**Issue by evelinekeh** [ghbonne/PMConverter#7]
"De start dates en end dates (zowel in de baseline schedule als in de tracking periods) in de geconverteerde ProTrack files (zie 'Project data input sheet_converted’ in bijlage) komen niet volledig overeen met deze die in de corresponderende Excel input sheet staan. Meer bepaald: de uren komen niet overeen. Als een bepaalde activiteit in de Excel sheet bv start om 8:00, dan wordt dit in de ProTrack file bv 15:59."

**Comment by GillesVandewiele** [comment]
Can someone link me a trace of this bug? I think this bug occurs in the XMLParser..

**Comment by ghbonne** [comment]
Found a bug of reading dates from Excel and fixed it in [commit](https://github.com/ghbonne/PMConverter/commit/d06cf660e21f404821dfd18a6af28392f6221379)
The issue was there that 17:00 was read as 16:59:59..., and the agenda expects datetimes rounded to the hour => added rounding of the read dates.
Idk if this has something to do with this bug, but I thought it would be best to share this also here.

**Comment by GillesVandewiele** [comment]
The dates are correctly converted to the project object (tested it with prints) and also to the xml file (<BaseLineStart>060320120800</BaseLineStart> e.g.), but are wrongly displayed in ProTrack. 

Though, for the Nursing Home Noordhinder the following fixed the bug:

- Clicking on the baseline start of the project activity with ID = 0 or WBS = 1
- Changing the baselinestart from 8:00:00 to 08:00:00 (changing it to 9:00:00 did the trick as well, so nothing wrong with the format..)

After this, all dates were set correctly..

**Comment by ghbonne** [comment]
I guess this bug was twofold:
1) The time part of the StartDate field in the p2x file sometimes gives an offset to all dates in ProTrack. -> fixed by removing the time part in that field
2) Excel Dates were not exactly read, e.g. 8:00 became 7:59:59.999 -> fixed by rounding input dates to  the hour
