### ISSUE TITLE
WBS column as additional input in Excel input sheet

### ISSUE THREAD

**Issue by ghbonne** [ghbonne/PMConverter#9]
Make the WBS column additional input in the new Excel format
Part of migrating to 1 new Excel format #6

**Comment by GillesVandewiele** [comment]
Jordy wil in de uiteindelijke Excel format, van de WBS kolom additional input maken, dus moeten we eerst checken of de wbs opgegeven is en zoja doen we gwn zoals in de huidige extended version
zo niet, dan voeren we het algoritme uit dat in de basic excel version nu gedaan wordt
